kubernetesClusterDomain: keel-prod.local

replicaCount: 3

deployment:
  hostname: src.kawfee.ca

  skaha:
    registryURL:
      - https://src.kawfee.ca/reg

    sessions:
      namespace: canfar-workloads
      kueue:
        rbac:
          create: true
        default:
          queueName: "skaha-local-queue"
          priorityClass: "high"
        headless:
          queueName: "skaha-local-queue"
          priorityClass: "low"