apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: src-kawfee-ca-reg-staging
  namespace: argocd
  labels:
    argocd.argoproj.io/domain: kawfee.ca
    argocd.argoproj.io/environment: staging
    argocd.argoproj.io/service: reg
spec:
  project: canfar
  sources:
    - repoURL: https://images-rc.canfar.net/chartrepo/library
      chart: reg
      targetRevision: 1.2.0
      helm:
        valueFiles:
          - $values/helm/values/src.kawfee.ca/reg/base.yaml
          - $values/helm/values/src.kawfee.ca/reg/staging.yaml
    - repoURL: https://github.com/at88mph/argocd-deploy.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: canfar-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
